syntax = "proto3";

package app;

/* layer custom */
message Geo {
    double lat = 1;
    double lng = 2;
}
message Landmark {
    float x = 1;
    float y = 2;
}

/* layer 2 */
message FaceResult { // 记录仪 -> 手机 float yaw = 1; float pitch = 2; float roll = 3; repeated int32 xyxy = 2;      
    repeated float feature = 1;
    bytes image = 2;
    float confidence = 3;
    repeated Landmark landmarks = 4;
}
message CarResult { // 记录仪 -> 手机
    string plate_number = 1;
    bytes image = 2;
}
message CigarettesResult { // 边缘 -> 手机 
    message Class {
        string class = 1;
        uint32 x1 = 2;
        uint32 x2 = 3;
        uint32 y1 = 4;
        uint32 y2 = 5;
    }
    repeated Class classes = 1;
    bytes image = 2;
}
message LicenseResult { // 边缘 -> 手机
    message Bbox {
        string text = 1;
        uint32 x1 = 2;
        uint32 x2 = 3;
        uint32 y1 = 4;
        uint32 y2 = 5;
    }
    repeated Bbox bboxes = 1;
    bytes image = 2;
}
message ShopSignResult {
    repeated string texts = 1;
}
message LawEnforceResult {
    repeated string texts = 1;
}

/* layer 1 */
message Handshake { // 记录仪, 边缘 -> 手机
    string id = 1; // "bodycam" "edge"
    string version = 2;
    string hardware_sn = 3;
    string activate_time = 4; // yyyyMMddHHmmss
}
message EdgeStatusReq {
}
message EdgeStatusResp {
    int32 temp = 1;
    float batter = 2;
}
message DetectReq { // 手机 -> 边缘
    enum Type {
        FACE = 0;           // 人脸
        CAR = 1;            // 车牌
        CIGARETTE = 2;      // 烟包
        LICENSE_BIZ = 3;    // 烟草证
        LICENSE_CIG = 4;    // 营业执照
        SHOP_SIGN = 5;      // 店招
        LAW_ENFORCE = 6;    // 亮证
    }
    repeated Type types = 1;
    bytes image = 2;
}
message DetectResp {
    CigarettesResult cigarettes_result = 1; // 边缘 -> 手机
    CarResult car_result = 2;               // 记录仪 -> 手机
    FaceResult face_result = 3;             // 记录仪 -> 手机
    LicenseResult license_result = 4;       // 边缘 -> 手机
    optional string id_schedule = 5;        // 手机 -> 服务器
    optional Geo geo = 6;                   // 手机 -> 服务器
    optional string id_retail = 7;          // 手机 -> 服务器
    ShopSignResult shop_sign_result = 8;
    LawEnforceResult law_enforce_result = 9;
    string timestamp = 10;                   // yyyyMMdd_HH-mm-ss-fff
}
message UpdateApp { // 手机 -> 记录仪, 边缘
    bytes file = 1;
    string version = 2;
    string md5 = 3;
    int32 size = 4;
}
message TaskNotice { // 手机 -> 记录仪
    bool status = 1; // true开始 false结束
    optional Geo geo = 2; // 任务开始时发送
}
message LawEnforceNotice { // 手机 -> 记录仪
    bool status = 1; // 是否识别亮证执法
}

/* layer 0 */
message Msg {
    oneof msg {
        Handshake handshake = 1;
        EdgeStatusReq edge_status_req = 2;
        EdgeStatusResp edge_status_resq = 3;
        DetectReq detect_req = 4;
        DetectResp detect_resp = 5;
        UpdateApp update_app = 6;
        TaskNotice task_notice = 7;
        LawEnforceNotice law_enforce_notice = 8;
    }
}