syntax = "proto3";

package vision;

// 握手消息
message Handshake {
    string name = 1;
    string version = 2;
    optional string sn = 3;
    optional string activate_time = 4; // yyyyMMddHHmmss
}

// 请求获取盒子状态
message EdgeStatusRequest {}

// 响应盒子状态请求
message EdgeStatusResponse {
    int32 temperature = 1;
    float battery = 2;
}

// 请求进行检测
message DetectRequest {
    enum Type {
        CIGARETTE_PACK = 0;
        LICENSE_BUSINESS = 1;
        LICENSE_TOBACCO = 2;
        LICENSE_SIGN = 3;
    }
    bytes image = 1;
    Type type = 2;
}

// 请求录制视频
message RecordRequest {}

// 零售户信息
message RetailInfo {
    message Location {
        double longitude = 1;   // 经度
        double latitude = 2;    // 纬度
    }
    optional string id = 1;
    optional string schedule = 2;
    optional Location location = 3;
}

// 亮证执法视频
message RecordVideo {
    bytes video = 1;
    bytes cover_image = 2;
}

// 升级包
message UpdateApp {
    bytes pack = 1;
    string version = 2;
    string md5 = 3;
    int32 size = 4;
}
