syntax = "proto3";

package vision;

message Handshake {
    enum Device {
        BODYCAM = 0;
        EDGE = 1;
        PHONE = 2;
        SERVER = 3;
    }
    Device device = 1;
    string version = 2;
    optional string hardware_sn = 3;
    optional string activate_time = 4;
}

message EdgeStatusRequest {}
message EdgeStatusResponse {
    float temperature = 1;
    float battery = 2;
}

message InferRequest {
    enum InferObj {
        FACE = 0;
        PLATE = 1;
        CIG_PACK = 2;
        CIG_LICENSE = 3;
        SHOP_LICENSE = 4;
        SHOP_SIGN = 5;
    }
    enum InferType {
        DET = 0;
        REC = 1;
    }
    bytes image = 1;
    InferObj obj = 2;
    InferType type = 3;
}
message InferResponse {
    message Point {
        int32 x = 1;
        int32 y = 2;
    }
    message Box {
        Point point = 1;
        int32 w = 2;
        int32 h = 3;
    }
    message Det {
        Box box = 1;
        float confidence = 2;
    }
    message FaceDet {
        Det det = 1;
        Point left_eye = 2;
        Point right_eye = 3;
        Point nose = 4;
        Point left_mouth = 5;
        Point right_mouth = 6;
    }
    message FaceRec {
        repeated float features = 1;
    }
    message PlateDet {
        Det det = 1;
        Point left_top = 2;
        Point right_top = 3;
        Point right_bottom = 4;
        Point left_bottom = 5;
    }
    message PlateRec {
        string number = 1;
    }
    message CigPackRec {
        int32 class = 1;
    }
    message TextRec {
        string text = 1;
    }
    repeated FaceDet     face_det = 1;
    repeated FaceRec     face_rec = 2;
    repeated PlateDet    plate_det = 3;
    repeated PlateRec    plate_rec = 4;
    repeated Det         cig_pack_det = 5;
    repeated CigPackRec  cig_pack_rec = 6;
    repeated Det         cig_license_det = 7;
    repeated TextRec     cig_license_rec = 8;
    repeated Det         shop_license_det = 9;
    repeated TextRec     shop_license_rec = 10;
    repeated Det         shop_sign_det = 11;
    repeated TextRec     shop_sign_rec = 12;
}

message DetectImage {
    repeated bytes face_images = 1;
    repeated bytes plate_images = 2;
}

message RecordRequest {}
message RecordResponse {
    bytes video = 1;
    bytes cover_image = 2;
}

message TaskNotice {
    bool status = 1;
}

message RetailInfo {
    message Geo {
        double lat = 1;
        double lng = 2;
    }
    string id = 1;
    string schedule = 2;
    Geo geo = 3;
}

message UpdateApp {
    bytes file = 1;
    string version = 2;
    string md5 = 3;
    int32 size = 4;
}

message Msg {
    oneof msg {
        Handshake handshake = 1;
        EdgeStatusRequest edge_status_request = 2;
        EdgeStatusResponse edge_status_response = 3;
        InferRequest infer_request = 4;
        InferResponse infer_response = 5;
        DetectImage detect_image = 6;
        RecordRequest record_request = 7;
        RecordResponse record_response = 8;
        TaskNotice task_notice = 9;
        RetailInfo retail_info = 10;
        UpdateApp update_app = 11;
    }
}
