syntax = "proto3";

package vision;

enum Device {
    BODYCAM = 0;
    EDGE = 1;
    PHONE = 2;
    SERVER = 3;
}

message Handshake {
    Device self = 1;
    string version = 2;
    optional string hardware_sn = 3;
    optional string activate_time = 4;
}

message EdgeBuzz {}

message EdgeStatusRequest {}
message EdgeStatusResponse {
    float temperature = 1;
    float battery = 2;
}

message InferRequest {
    enum Type {
        FACE = 0;           // 人脸
        PLATE = 1;          // 车牌
        CIG_PACK = 2;       // 烟包
        CIG_LICENSE = 3;    // 烟草证
        SHOP_LICENSE = 4;   // 营业执照
        SHOP_SIGN = 5;      // 店铺招牌
        LAW_ENFORCE = 6;    // 亮证执法
    }
    bytes image = 1;
    repeated Type types = 2;
}
message InferResponse {
    message Box {
        message Point {
            int32 x = 1;
            int32 y = 2;
        }
        Point point = 1;
        int32 w = 2;
        int32 h = 3;
    }
    message Face {
        repeated float features = 1;
        bytes image = 2;
    }
    message Plate {
        string number = 1;
        bytes image = 2;
    }
    message CigPack {
        int32 class = 1;
        Box box = 2;
    }
    message CigLicense {
        string text = 1;
        Box box = 2;
    }
    message ShopLicense {
        string text = 1;
        Box box = 2;
    }
    message ShopSign {
        string text = 1;
    }
    message LawEnforce {
        string text = 1;
    }
    repeated Face faces = 1;
    repeated Plate plates = 2;
    repeated CigPack cig_packs = 3;
    repeated CigLicense cig_licenses = 4;
    repeated ShopLicense shop_licenses = 5;
    repeated ShopSign shop_signs = 6;
    repeated LawEnforce law_enforces = 7;
}

message RecordRequest {}
message RecordResponse {
    bytes video = 1;
    bytes cover_image = 2;
}

message TaskNotice {
    bool status = 1; // true开始 false结束
}

message RetailInfo {
    message Geo {
        double lat = 1;
        double lng = 2;
    }
    string id = 1;
    string schedule = 2;
    Geo geo = 3;
}

message UpdateApp {
    bytes file = 1;
    string version = 2;
    string md5 = 3;
    int32 size = 4;
}

// 顶层结构，所有消息在这里包装
message Msg {
    Device target = 1;
    oneof msg {
        Handshake handshake = 2;
        EdgeBuzz edge_buzz = 3;
        EdgeStatusRequest edge_status_request = 4;
        EdgeStatusResponse edge_status_response = 5;
        InferRequest infer_request = 6;
        InferResponse infer_response = 7;
        RecordRequest record_request = 8;
        RecordResponse record_response = 9;
        TaskNotice task_notice = 10;
        RetailInfo retail_info = 11;
        UpdateApp update_app = 12;
    }
}

message Broadcast {
    string ssid = 1;
    string password = 2;
}
